# Generated by Django 2.1.2 on 2018-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='value',
            new_name='value1',
        ),
        migrations.AddField(
            model_name='number',
            name='value2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='number',
            name='value3',
            field=models.IntegerField(default=0),
        ),
    ]
