// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $BlogPostλShape = $.typeutil.flatten<_std.$Object_169a5ce7108a11eeb5af6feb88c88f11λShape & {
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, true>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "created_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, true, true>;
  "updated_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $BlogPost = $.ObjectType<"default::BlogPost", $BlogPostλShape, null, [
  ..._std.$Object_169a5ce7108a11eeb5af6feb88c88f11['__exclusives__'],
]>;
const $BlogPost = $.makeType<$BlogPost>(_.spec, "37f021f0-11d7-11ee-88e4-a3a5f98eeed6", _.syntax.literal);

const BlogPost: $.$expr_PathNode<$.TypeSet<$BlogPost, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($BlogPost, $.Cardinality.Many), null);



export { $BlogPost, BlogPost };

type __defaultExports = {
  "BlogPost": typeof BlogPost
};
const __defaultExports: __defaultExports = {
  "BlogPost": BlogPost
};
export default __defaultExports;
