version: '3.4'

services:
  rabbitmq:
    restart: always
    build: ./docker
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER:?set RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:?set RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST:-practice}
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
