/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/zrma/Documents/Code/PolyGlot/NimPractice/test/nimcache/stdlib_parseutils.o /Users/zrma/Documents/Code/PolyGlot/NimPractice/test/nimcache/stdlib_parseutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, parseSaturatedNatural_heAOnV8CAiOgwhPKbfpRgA)(NimStringDesc* s, NI* b, NI start) {
	NI result;
	NI i;
	nimfr_("parseSaturatedNatural", "parseutils.nim");
	result = (NI)0;
	nimln_(283, "parseutils.nim");
	i = start;
	nimln_(284, "parseutils.nim");
	{
		NI TM_vI9aZNKIcImom6dDyKXW1ZA_2;
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA3_;
		TM_vI9aZNKIcImom6dDyKXW1ZA_2 = addInt(i, ((NI) 1));
		i = (NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_2);
	}
	LA3_: ;
	nimln_(285, "parseutils.nim");
	{
		NI TM_vI9aZNKIcImom6dDyKXW1ZA_10;
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA7_;
		nimln_(286, "parseutils.nim");
		(*b) = ((NI) 0);
		{
			nimln_(287, "parseutils.nim");
			while (1) {
				NI c;
				NI TM_vI9aZNKIcImom6dDyKXW1ZA_3;
				NI TM_vI9aZNKIcImom6dDyKXW1ZA_8;
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA10;
				nimln_(288, "parseutils.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				TM_vI9aZNKIcImom6dDyKXW1ZA_3 = subInt(((NU8)(s->data[i])), ((NI) 48));
				c = (NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_3);
				nimln_(289, "parseutils.nim");
				{
					NI TM_vI9aZNKIcImom6dDyKXW1ZA_4;
					NI TM_vI9aZNKIcImom6dDyKXW1ZA_5;
					NI TM_vI9aZNKIcImom6dDyKXW1ZA_6;
					NI TM_vI9aZNKIcImom6dDyKXW1ZA_7;
					TM_vI9aZNKIcImom6dDyKXW1ZA_4 = subInt(((NI) IL64(9223372036854775807)), c);
					TM_vI9aZNKIcImom6dDyKXW1ZA_5 = divInt((NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_4), ((NI) 10));
					if (!((*b) <= (NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_5))) goto LA13_;
					nimln_(290, "parseutils.nim");
					TM_vI9aZNKIcImom6dDyKXW1ZA_6 = mulInt((*b), ((NI) 10));
					TM_vI9aZNKIcImom6dDyKXW1ZA_7 = addInt((NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_6), c);
					(*b) = (NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_7);
				}
				goto LA11_;
				LA13_: ;
				{
					nimln_(292, "parseutils.nim");
					(*b) = ((NI) IL64(9223372036854775807));
				}
				LA11_: ;
				nimln_(293, "parseutils.nim");
				TM_vI9aZNKIcImom6dDyKXW1ZA_8 = addInt(i, ((NI) 1));
				i = (NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_8);
				{
					nimln_(294, "parseutils.nim");
					while (1) {
						NI TM_vI9aZNKIcImom6dDyKXW1ZA_9;
						if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
						if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA17;
						TM_vI9aZNKIcImom6dDyKXW1ZA_9 = addInt(i, ((NI) 1));
						i = (NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_9);
					} LA17: ;
				}
			} LA10: ;
		}
		nimln_(295, "parseutils.nim");
		TM_vI9aZNKIcImom6dDyKXW1ZA_10 = subInt(i, start);
		result = (NI)(TM_vI9aZNKIcImom6dDyKXW1ZA_10);
	}
	LA7_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void) {
	nimfr_("parseutils", "parseutils.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void) {
}

